# Generated by Django 5.0.6 on 2024-08-13 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=10)),
                ('customer', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=10)),
                ('project_type', models.CharField(max_length=10)),
                ('project_category', models.CharField(max_length=15)),
                ('proposal_code', models.CharField(max_length=50)),
                ('rfp_received_date', models.DateField()),
                ('response_submission_date', models.DateField()),
                ('bd_spoc', models.EmailField(max_length=254)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cas_no', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(max_length=10)),
                ('target_molecule_spec', models.CharField(max_length=100)),
                ('is_techpack_available', models.BooleanField()),
                ('phase', models.CharField(max_length=10)),
                ('oel_value', models.FloatField()),
                ('molecular_structure', models.FileField(blank=True, null=True, upload_to='molecular_structures/')),
                ('quantity', models.FloatField()),
                ('purity', models.FloatField()),
                ('techpack_attachments', models.FileField(blank=True, null=True, upload_to='techpack_attachments/')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compounds', to='aragen_app.proposal')),
            ],
        ),
    ]
