# Generated by Django 5.0.6 on 2024-08-16 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aragen_app', '0002_role_user_delete_compound_delete_proposal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='id',
            new_name='role_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='role_id',
        ),
    ]
