# Generated by Django 5.0.6 on 2024-08-16 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aragen_app', '0003_rename_id_role_role_id_rename_role_user_role_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role_id',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='aragen_app.role'),
            preserve_default=False,
        ),
    ]
